OS_DETECTION_ENABLE = yes
SPLIT_DETECTED_OS_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes

ENCODER_MAP_ENABLE = yes
SERIAL_DRIVER = vendor
WS2812_DRIVER = vendor
OLED_DRIVER = ssd1306

SRC += graphics/oled.c